---
branches:
  only:
  - master

services: docker

language: python
python: "2.7"

env:
#  - distro: centos8
#    init: /usr/lib/systemd/systemd
  - distro: centos7
    init: /usr/lib/systemd/systemd
  - distro: ubuntu1604
    init: /lib/systemd/systemd
  - distro: ubuntu1804
    init: /lib/systemd/systemd

before_install:
  # Pull container.
  - 'docker pull grycap/travis:${distro}'

script:
  - container_id=$(mktemp)
  # Run container in detached state.
  - 'docker run -t --detach --privileged --hostname htcondoreserver --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/role_under_test:ro grycap/travis:${distro} "${init}" > "${container_id}"'

  # install dependencies
  - 'docker exec "$(cat ${container_id})" ansible-galaxy install --ignore-certs geerlingguy.ntp grycap.ssh'

  # Ansible syntax check.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml --syntax-check'

  # Test role installation.
  - 'docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml -e "network_interface=172.17.0.2 htcondor_vnode_prefix=wn"'
  - 'docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml -e "htcondor_type_of_node=wn"'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
