---
- name: Include "{{ansible_os_family}}" tasks
  include: "{{ansible_os_family}}.yaml"

- name: Copy 'is_cluster_ready' file
  copy: dest=/bin/is_cluster_ready src=is_cluster_ready mode=0755 force=no

- name: Set hostname
  command: hostname {{htcondor_server_name}}

- name: Manage the /etc/hosts file
  shell: |
    for i in `seq 1 {{max_number_of_nodes}}`; do
      item="{{vnode_prefix}}${i}";
      grep -q "\<${item}\>" /etc/hosts || echo "127.0.0.1 ${item} ${item}.localdomain" >> /etc/hosts;
    done

- file: path=/etc/clues2 state=directory mode=0755
- copy:
    content: |
       {% for number in range(1, max_number_of_nodes|int + 1) %}
       {{vnode_prefix}}{{number}}.localdomain
       {% endfor %}
    dest: "/etc/clues2/condor_vnodes.info"
  
- lineinfile: dest=/etc/condor/condor_config regexp=REQUIRE_LOCAL_CONFIG_FILE line="REQUIRE_LOCAL_CONFIG_FILE=TRUE"

- copy:
    content: |
       CONDOR_HOST = htcondoreserver
       BIND_ALL_INTERFACES = FALSE
       NETWORK_INTERFACE = {{IM_NODE_NET_0_IP}}
       ALLOW_WRITE = htcondoreserver, vnode*.localdomain
       DAEMON_LIST = MASTER, STARTD
    dest: "/etc/condor/condor_config.local"

- lineinfile: dest=/etc/condor/condor_config.local regexp=DAEMON_LIST line="DAEMON_LIST = MASTER, COLLECTOR, NEGOTIATOR, SCHEDD"
- lineinfile: dest=/etc/condor/condor_config.local regexp=NETWORK_INTERFACE line="NETWORK_INTERFACE = {{IM_NODE_NET_1_IP}}"
- lineinfile: dest=/etc/condor/condor_config.local regexp=NEGOTIATOR_INTERVAL line="NEGOTIATOR_INTERVAL = 30"
- lineinfile: dest=/etc/condor/condor_config.local regexp=NEGOTIATE_ALL_JOBS_IN_CLUSTER line="NEGOTIATE_ALL_JOBS_IN_CLUSTER = True"

- service: name=condor state=restarted
