---
- set_fact:
    gpgcheck: yes
  when: htcondor_rpm_repo_gpg_key_url != ""

- set_fact:
    gpgcheck: no
  when: htcondor_rpm_repo_gpg_key_url == ""

- yum_repository:
    name: "htcondor"
    description: "HTCondor RPM Repository"
    file: "htcondor"
    baseurl: "{{ htcondor_rpm_repo_base_url }}"
    enabled: yes
    priority: 1
    gpgcheck: "{{ gpgcheck }}"

- name: import gpg key
  rpm_key:
    key: "{{ htcondor_rpm_repo_gpg_key_url }}"
    state: present
  when: htcondor_rpm_repo_gpg_key_url != ""

- name: Yum install EPEL
  yum: name=epel-release

- name: Yum install condor in REL 7- system
  yum: name=condor,condor-python,globus-gss-assist
  when: ansible_distribution_major_version|int < 8

- block:
  - name: enable PowerTools repo
    yum_repository:
      name: powertools
      description: CentOS Linux $releasever - PowerTools
      file: CentOS-Linux-PowerTools
      baseurl: http://mirror.centos.org/$contentdir/$releasever/PowerTools/$basearch/os/
      mirrorlist: http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=PowerTools&infra=$infra
      enabled: yes
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial
      gpgcheck: yes

  - name: Yum install boost-python3 in REL 8+ system
    yum: name=boost-python3 update_cache=yes

  - name: Yum install condor in REL 8+ system
    yum: name=condor,python3-condor,globus-gss-assist
  
  when: ansible_distribution_major_version|int >= 8
