---
- set_fact:
    gpgcheck: yes
  when: htcondor_rpm_repo_gpg_key_url != ""

- set_fact:
    gpgcheck: no
  when: htcondor_rpm_repo_gpg_key_url == ""

- yum_repository:
    name: "htcondor"
    description: "HTCondor RPM Repository"
    file: "htcondor"
    baseurl: "{{ htcondor_rpm_repo_base_url }}"
    enabled: yes
    priority: 1
    gpgcheck: "{{ gpgcheck }}"

- name: import gpg key
  rpm_key:
    key: "{{ htcondor_rpm_repo_gpg_key_url }}"
    state: present
  when: htcondor_rpm_repo_gpg_key_url != ""

- name: Yum install EPEL
  yum: name=epel-release

- name: Yum install condor in REL system
  yum: name=condor,condor-python,globus-gss-assist

