---
- copy:
    content: |
           CONDOR_HOST = {{ htcondor_server }}
           DAEMON_LIST = MASTER,STARTD
           ## Always run jobs
           START = True
           SUSPEND = False
           CONTINUE = True
           PREEMPT = False
           KILL = False
    dest: "/etc/condor/condor_config.local"
  notify: restart htcondor

- service: name=condor state=started
